// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[]           = "ad170d85-6f98-4191-8a2c-8534d9bb35f3";
const char DEVICE_LOGIN_NAME[]  = "443fe440-5ef0-4a9b-a8ca-d8676a255841";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password


float centrTemp;
int vaha;
float perifTemp;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(centrTemp, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(vaha, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(perifTemp, READ, 1 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
